package testConnectFourGame;

import org.junit.jupiter.api.Test;

import connectFourGame.Game;
import systemClass.ProjectScanner;

import static org.junit.Assert.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.FileDescriptor;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

public class TestGame{
	@Test
	public void testStart1() {
		provideInputStream("abc\n4\n1\nSONG\nx\nSONG\no\nRui\nx\nRui\no\n-1\n-3\n-2\n-2\n-2\nabc\n7\n3\n3\n3\n3\n3\n3\n3\n4\n5\n-1\n-3\n-1\n-1\n5\n4\n5\n4\n5\n4\n5\n");
		
		PrintStream originalOut = System.out;
		try {
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			System.setOut(new PrintStream(outputStream));

			Game game = new Game();
			
			String output = outputStream.toString();
			assertEquals("Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please enter a valid integer number!\r\n"
					+ "Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please type in Player 1's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): Please type in Player 2's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): The two players cannot have the same name or symbol! Please set the second player's the name and symbol again.\r\n"
					+ "Please type in Player 2's name: Please type in a char represent to Rui's chess (e.g. 'o', 'x'): The two players cannot have the same name or symbol! Please set the second player's the name and symbol again.\r\n"
					+ "Please type in Player 2's name: Please type in a char represent to Rui's chess (e.g. 'o', 'x'): \r\n"
					+ "New game started! The symbol for SONG is 'x', for Rui is 'o'.\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: You cannot undo now! \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: You cannot redo now! \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: BetaGo, the AI player, is thinking...\r\n"
					+ "BetaGO's suggestion: 3\r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "GamaGo's suggestion: 3\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (1 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: BetaGo, the AI player, is thinking...\r\n"
					+ "BetaGO's suggestion: 3\r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "GamaGo's suggestion: 3\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: You have no more chance to get Suggestion!\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: Please enter an integer number! \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: Input is out of range 0-6. Please try again.\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: Column 3 is already full. Please try again.\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x x o   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x x o   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection: You have no more chance to undo!\r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x   x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o   x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o o x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x   x   |\r\n"
					+ "|       o o x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x o x   |\r\n"
					+ "|       o o x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (0 more times) \r\n"
					+ "     -2: Get AI suggestion (0 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o   x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "|       o o x   |\r\n"
					+ "|       x o x   |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "'x' has got 4 Vertical Adjacencies.\r\n"
					+ "Congrats to SONG on the win!\r\n"
					+ ""
	                    , output);
		}
		finally
    	{
    		System.setOut(originalOut);
    		restoreSystemIn();
    	}
	}
	
	@Test
	public void testStart2() {
		provideInputStream("1\nSONG\nx\nRui\no\n3\n3\n3\n3\n3\n3\n2\n2\n2\n2\n2\n2\n4\n4\n4\n4\n4\n4\n0\n1\n1\n1\n1\n1\n1\n0\n0\n0\n0\n0\n6\n5\n5\n5\n5\n5\n5\n6\n6\n6\n6\n6\n");
		
		PrintStream originalOut = System.out;
		try {
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			System.setOut(new PrintStream(outputStream));

			Game game = new Game();
			
			String output = outputStream.toString();
			assertEquals("Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please type in Player 1's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): Please type in Player 2's name: Please type in a char represent to Rui's chess (e.g. 'o', 'x'): \r\n"
					+ "New game started! The symbol for SONG is 'x', for Rui is 'o'.\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
					+ "Please select an option from the following list: \r\n"
					+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|       o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|       x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|       o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x       |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o       |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "| x   x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|     o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|     x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|     o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|   x o o o     |\r\n"
					+ "|   o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|   x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x   x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
					+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x     |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o     |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o   |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x   |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Rui, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "| o x o o o x o |\r\n"
					+ "| x o x x x o x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Congrats to Rui on the win!\r\n"
                    , output);
		}
		finally
    	{
    		System.setOut(originalOut);
    		restoreSystemIn();
    	}
	}
	
	@Test
	public void testStart3() {
		provideInputStream("2\nSONG\nx\n1\n6\n6\n5\n4\n");

		PrintStream originalOut = System.out;
		try {
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			System.setOut(new PrintStream(outputStream));
			
			Game game = new Game();

			String output = outputStream.toString();
			assertEquals("Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please type in Player 1's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): "
					+ "Please select the AI player you want to play against: \r\n"
					+ "   1. GamaGo (Easy) \r\n"
					+ "   2. BetaGO (Hard) \r\n"
					+ "Enter the index number to indicate the AI Model to play against: Please type in Player 2's name: GamaGo\r\n"
					+ "Please type in a char to represent GamaGo's chess (e.g. 'o', 'x'): o\r\n"
					+ "\r\n"
					+ "New game started! The symbol for SONG is 'x', for GamaGo is 'o'.\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       o     x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "|       o     x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "|     o o     x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "|     o o   x x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "|   o o o   x x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "|   o o o x x x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "GamaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|             x |\r\n"
					+ "| o o o o x x x |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "'o' has got 4 Horizontal Adjacencies.\r\n"
					+ "Congrats to GamaGo on the win!\r\n"
					+ ""
	                    , output);
		}
		finally
    	{
    		System.setOut(originalOut);
    		restoreSystemIn();
    	}
	}
	
	@Test
	public void testStart4() {
		provideInputStream("3\n2\nSONG\nx\nSONG\no\n6\n6\n6");

		PrintStream originalOut = System.out;
		try {
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			System.setOut(new PrintStream(outputStream));
			
			Game game = new Game();
			
			String output = outputStream.toString();
			assertEquals("Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please select the AI player you want to play against: \r\n"
					+ "   1. GamaGo (Easy) \r\n"
					+ "   2. BetaGO (Hard) \r\n"
					+ "Enter the index number to indicate the AI Model to play against: Please type in Player 1's name: BetaGo\r\n"
					+ "Please type in a char to represent BetaGo's chess (e.g. 'o', 'x'): x\r\n"
					+ "Please type in Player 2's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): The two players cannot have the same name or symbol! Please set the second player's the name and symbol again.\r\n"
					+ "Please type in Player 2's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): \r\n"
					+ "New game started! The symbol for BetaGo is 'x', for SONG is 'o'.\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "'x' has got 4 Vertical Adjacencies.\r\n"
					+ "Congrats to BetaGo on the win!\r\n"
					+ ""
	                    , output);
		}
		finally
    	{
    		System.setOut(originalOut);
    		restoreSystemIn();
    	}
	}
	
	@Test
	public void testToString() {
		provideInputStream("3\n2\nSONG\no\n1\n6\n6\n5\n4\n");
		
		Game game = new Game();
		LocalTime currentTime = LocalTime.now();
		
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
		
		assertEquals(currentTime.format(formatter) + " | "
					+ "BetaGo" + "(" + "x" + ") vs. "
					+ "SONG" + "(" + "o" + ")"
                    , game.toString());
		
		restoreSystemIn();
	}
	
	@Test
	public void testViewGame() {		
		provideInputStream("3\n2\nSONG\no\n6\n6\n6\n-1\n");

		PrintStream originalOut = System.out;
		try {
			ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
			System.setOut(new PrintStream(outputStream));
			
			Game game = new Game();
			LocalTime currentTime = LocalTime.now();
			
			game.viewGame();
			DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
			
			String output = outputStream.toString();
			assertEquals("Please select game mode: \r\n"
					+ "   1. Human vs Human \r\n"
					+ "   2. Human vs AI \r\n"
					+ "   3. AI vs Human \r\n"
					+ "Enter the index number to indicate the game mode: Please select the AI player you want to play against: \r\n"
					+ "   1. GamaGo (Easy) \r\n"
					+ "   2. BetaGO (Hard) \r\n"
					+ "Enter the index number to indicate the AI Model to play against: Please type in Player 1's name: BetaGo\r\n"
					+ "Please type in a char to represent BetaGo's chess (e.g. 'o', 'x'): x\r\n"
					+ "Please type in Player 2's name: Please type in a char represent to SONG's chess (e.g. 'o', 'x'): \r\n"
					+ "New game started! The symbol for BetaGo is 'x', for SONG is 'o'.\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "SONG, it's your turn.\r\n"
	        		+ "Please select an option from the following list: \r\n"
	        		+ "    0-6: Place A New Piece At The Input Position \r\n"
					+ "     -1: To Undo The Last Step (1 more times) \r\n"
					+ "     -2: Get AI suggestion (2 more times) \r\n"
					+ "     -3: Redo The Last Step \r\n"
					+ "Please enter your selection:   --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "BetaGo, the AI player, is thinking...\r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|       x       |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "|       x     o |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "'x' has got 4 Vertical Adjacencies.\r\n"
					+ "Congrats to BetaGo on the win!\r\n"
					+ "\r\n"
					+ "You are now traversing the game in "+currentTime.format(formatter)+" between Player1, BetaGo(x),  and Player2, SONG(o). \r\n"
					+ "  --------------\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "|               |\r\n"
					+ "  --------------\r\n"
					+ "  0 1 2 3 4 5 6 \r\n"
					+ "Enter 1 for the last move, 2 for the next move, 0 for AI suggestion for the next move, -1 for exit: "
                    , output);
		}
		finally
    	{
    		System.setOut(originalOut);
    		restoreSystemIn();
    	}
	}
	
    private void provideInputStream(String input) {
    	//System.out.print(input);
        InputStream sysInBackup = System.in; // Backup System.in to restore it later
        ByteArrayInputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        // Use reflection to set the scanner field
        try {
            Field scannerField = ProjectScanner.class.getDeclaredField("scanner");
            scannerField.setAccessible(true);
            scannerField.set(ProjectScanner.getInstance(), new Scanner(System.in));
        } catch (NoSuchFieldException | IllegalAccessException e) {
            e.printStackTrace();
        }

        System.setIn(sysInBackup); // Restore original System.in
    }
    
    private void restoreSystemIn() {
        // Restore original System.in
        System.setIn(new FileInputStream(FileDescriptor.in));
    }
}